[project]
name = "clusterexp"
version = "0.1.0"
description = "Clustering Experiments"
readme = "README.md"
authors = [
    {name = "Natacha Galmiche", email = "natacha.galmiche@uib.no"}
]
license = "MIT"
license-files = ["LICENSE.txt"]
keywords = ["clustering", "time-series", "internal cluster validity indices", "CVI", "machine learning"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",

    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

requires-python = ">=3.14"

dependencies = [
    "kmedoids>=0.5.5",
    "matplotlib>=3.10.9",
    # "pycvi-lib>=1.0.0",
    "pycvi-lib",
    "scikit-learn>=1.7.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

# -------------------------------------------------------
#  ------------------ UV configuration ------------------
# -------------------------------------------------------


[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "clusterexp"
module-root = ""

[tool.uv.sources]
pycvi-lib = { git = "https://github.com/nglm/pycvi.git", branch = "docs" }


